buildscript {
    ext.kotlin_version = '2.2.0'
    ext.kotlin_coroutines_version = '1.10.2'
    ext.compose_bom = "2025.11.00"
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
plugins {
    id 'org.jetbrains.kotlin.jvm' version "$kotlin_version" apply false
    id "org.jetbrains.kotlin.plugin.compose" version "$kotlin_version"
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

ext {
    compileSdk = 36
    minSdk = 21
    targetSdk = 36

    versionCode = 80
    versionName = "0.17.8"

    groupId = "io.github.dadino.quickstart3"

    sonatypeStagingProfileId = System.properties['sonatypeStagingProfileId']
    ossrhToken = System.properties['ossrhToken']
    ossrhTokenPassword = System.properties['ossrhTokenPassword']
}
