package com.dadino.quickstart3.core.entities

/**
 * `Signal` instances are generated by the QuickLoop
 * and dispatched to the UI layer.  These signals trigger one-time actions within the UI,
 * such as displaying a dialog, navigating to a different screen, or updating UI elements
 * based on changes in the application state.
 */
open class Signal
